### ISSUE TITLE
dropdown menu invisible

### ISSUE THREAD

**Issue by rw0007** [clemdesign/grav-plugin-language-selector#2]
The button displays in the upper right corner of the page. By selecting the button the dropdown is not opening. In HTML code all elements are available and by disabling the build-in CSS the button plus the dropdown menu is visible and functioning. An error message says 'user-select' declaration unknown and ignored. It looks that there is an issue with the JS-code.

**Comment by foufrix** [comment]
I had the same problem as you. The problem is not from the plugin but from your site settings.

In admin panels go to configuration then the system page, go to translation and add the language you want to put (i tried en, fr , es) and everything work fine.

cf screenshot for detail

![screenshot 2018-01-04 at 17 49 50](https://user-images.githubusercontent.com/16646581/34550680-b67f7692-f177-11e7-8d86-2e9d2b6d175f.png)

**Comment by clemdesign** [comment]
Hi, sorry for the late, I have'nt activated the good email option to follow this issue :confused: 

So, @foufrix is right. You should define the list of languages in config page. Do you have resolved your issue?

**Comment by alejandrosanchezortiz** [comment]
Hi, 
Most probably his problem was that he forgot to include JQuery library . Because I had the same problem but I fixed it easily

**Comment by henryoddi** [comment]
Thank you so much @alejandrosanchezortiz for your suggestion - I was able to manually add the jQuery library (make sure it is being parsed before the language-selector library) -- see [this resource for details on priority of loading scripts](https://stackoverflow.com/questions/2194992/jquery-is-not-defined). This solved my problem! A simple bug identified to fix for future versions, too!

Thanks again @clemdesign for your excellent plugin.

**Comment by clemdesign** [comment]
Hi everybody,

So, after your comments, I improved the jQuery integration, available in 1.0.1 version. Maybe this action resolve your issues because on my side, the behavior is not visible.

To resume:
  * This plugin need jQuery to work correctly (Normally [preconfigured](https://learn.getgrav.org/themes/asset-manager#named-assets) in Grav).
  * I improved jQuery integration, like suggested @henryoddi .
  * I consider that this issue is closed.

**Comment by lokipo** [comment]
Sorry to bring this up again, but I have the same problem, configured the plugin correctly, cannot see the dropdown-menu.
How do I "include jquery"? AFAIK my site already includes that, it should also be loaded and be the correct version.

**Comment by clemdesign** [comment]
You can add it through:

- [System configuration](https://learn.getgrav.org/16/admin-panel/dashboard/configuration-system#assets) (Admin panel) or
- [Your theme](https://learn.getgrav.org/16/themes/asset-manager)

**Comment by lokipo** [comment]
Thank you for your quick response, I did enable jquery in config and tried to use language selector like:

{% block javascripts %}
        {% do assets.addJs('jquery', 101) %}
        {% include 'partials/language-selector.html.twig' %}
 {% endblock %}

Unfortunately, still nothing.
My grav installation uses jquery-2.x.min.js, is that the culprit, maybe?

**Comment by clemdesign** [comment]
Maybe the following steps will help you:
- Show source code (Ctrl + U / Option + Command + U)
- In top JS implementation, check that your jQuery is integrated first. I'm currently use v2.2.4 of jQuery but should be works with more recent version.
- In top JS implementation again, check that the language selector JS is integrated. Look for "Language Selector JS plugin" text in JS files.
- If your implementation is correct but doesn't work, try with jQuery 2.2.4.
